# .github/workflows/deploy.yml

name: Node.js CI

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/deploy.yml'
      - 'apptest/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/deploy.yml'
      - 'apptest/**'

env:
  WORKDIR: apptest

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [18.x]

    defaults:
      run:
        working-directory: apptest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
       
      - run: rm -rf node_modules yarn.lock package-lock.json
      - run: npm install
      - run: npm run  build   

      - run: tar zcvf  osdoc.tar.gz build   
      - name: upload artificts
        uses: actions/upload-artifact@v2
        with:
         name: osdoc.tar.gz
         path: osdoc.tar.gz
      
      - uses: svenstaro/upload-release-action@v2
        id: release
        with:
           token: ${{ secrets.GITHUB_TOKEN }}
           file: osdoc.tar.gz
           tag: ${{ github.ref }}
           release_name: ${{ github.ref }}
           overwrite: true
           file_glob: true
           body: ""