# .github/workflows/deploy.yml

name: Node.js CI

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/deploy.yml'
      - 'apptest/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/deploy.yml'
      - 'apptest/**'

env:
  WORKDIR: apptest

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [18.x]

    defaults:
      run:
        working-directory: apptest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
       
      - run: rm -rf node_modules yarn.lock package-lock.json
      - run: npm install
      - run: npm run  build   

      - run: tar zcvf  osdoc.tar.gz build   
      - name: upload artificts
        uses: actions/upload-artifact@v2
        with:
         name: osdoc.tar.gz
         path: osdoc.tar.gz
      
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
           token: ${{ secrets.GITHUB_TOKEN }}
           release-type: node
           package-name: standard-version
           changelog-types: '[{"type": "types", "section":"Types", "hidden": false},{"type": "revert", "section":"Reverts", "hidden": false},{"type": "feat", "section": "Features", "hidden": false},{"type": "fix", "section": "Bug Fixes", "hidden": false},{"type": "improvement", "section": "Feature Improvements", "hidden": false},{"type": "docs", "section":"Docs", "hidden": false},{"type": "style", "section":"Styling", "hidden": false},{"type": "refactor", "section":"Code Refactoring", "hidden": false},{"type": "perf", "section":"Performance Improvements", "hidden": false},{"type": "test", "section":"Tests", "hidden": false},{"type": "build", "section":"Build System", "hidden": false},{"type": "ci", "section":"CI", "hidden":false}]' 
