# .github/workflows/deploy.yml

name: nodejs CI

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/npm-publish.yml'
      - 'apptest/**'

env:
  WORKDIR: apptest

jobs:
  deploy:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: apptest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: actions/checkout@v3
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ env.WORKDIR }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.WORKDIR }}-

      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: Deploy
        uses: hopefulchen/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ env.WORKDIR }}/build
          cname: 'test-docusaurus.apptest.com'
          allow_empty_commit: true
